name: 🐞 错误报告
description: 当出现问题时提交报告以便修复！
title: '🐞 错误报告: xxx.md'
labels: ['request']
assignees: jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        注意：请求太多，请按照下面内容提供错误报告  
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   

  - type: input
    id: error-list
    attributes:
      label: 📄 错误清单
      description: 指定错误清单文件，方便我们快速定位错误。
      placeholder: ex. `docs/ansible.md`
    validations:
      required: true

  - type: checkboxes
    id: error-type
    attributes:
      label: 🧨 错误类型
      description: 请选择错误类型。
      options:
        - label: 排版 & 文字错误
        - label: 清单内容示例错误
        - label: 其它
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📖 错误说明
      description: 您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的备忘清单(速查表)。
      placeholder: 请您在这里详细介绍具体错误问题
    validations:
      required: true