name: 🤙 备忘清单请求
description: 请求添加备忘清单和参考
title: '【备忘清单】 请求: <Name>'
labels: ['request']
assignees: jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        注意：请求太多，参考【优先级】快速添加内容  
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        
        ### 优先级
        
        - 提交 PR 优先合并(优先处理)
        - 提供可复制的[中文/英文]备忘清单资料，优先添加
        - 大众化的内容(java/python)，优先搬运(小众内容请提供资料)

  - type: textarea
    id: description
    attributes:
      label: 说明项目
      description: 您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的备忘清单(速查表)。
      placeholder: 【请您在这里介绍一下工具或者语言，这很重要】
    validations:
      required: true
      
  - type: input
    id: official-website
    attributes:
      label: 提供官网
      description: 提供官网网站有助于我们整理成备忘清单(速查表)
      placeholder: ex. https://xxx.com

  - type: markdown
    attributes:
      value: |
        _⚠️ 注意: 随着内容越来越多，可能甚至找不到这个工具或者语言的官网，请您在这里提供以便大家共同参与贡献内容_

  - type: textarea
    id: reference-url
    attributes:
      label: 参考资料 URL
      description: 提供更多参考资料有助于我们整理成备忘清单(速查表)
      placeholder: |
        https://jaywcjlove.github.io/reference
        https://jaywcjlove.github.io/reference
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        _⚠️ 注意: 提供更多参考资料，以便大家共同参与贡献内容_
