name: UpdateFormUp

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次，时间为UTC 00:00
  workflow_dispatch:  # 手动触发

jobs:
  update-dockerinstall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: update
      run: |          
          git remote add upstream https://github.com/jaywcjlove/reference.git
          git fetch upstream
          git checkout main  # 如果你的主分支不是main，改为对应分支
          git merge upstream/main --allow-unrelated-histories
          git push origin main
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
